<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="DESKTOP-RL8SVL3" failures="1" tests="3" name="Test(failed)" time="0.008" errors="0" timestamp="2023-07-24T07:03:21 IST">
  <testcase classname="testNgg.RetryAnalyz" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="testNgg.RetryAnalyz" name="Test1" time="0.0">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="testNgg.RetryAnalyz" name="Test1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNgg.RetryAnalyz.Test1(RetryAnalyz.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at testNgg.RunFailedTestCases.runFailedTests(RunFailedTestCases.java:21)
... Removed 55 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="testNg.RetryAnalyz" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
  <testcase classname="testNg.RetryAnalyz" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNgg.RetryAnalyz" name="Test2" time="0.0">
    <ignored/>
  </testcase> <!-- Test2 -->
</testsuite> <!-- Test(failed) -->
